"""5322de03abd4

Revision ID: 2967de5da23a
Revises: 5322de03abd4
Create Date: 2023-04-08 13:33:16.104649

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2967de5da23a'
down_revision = '5322de03abd4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Form', schema=None) as batch_op:
        batch_op.drop_column('date_delete')
        batch_op.drop_column('date_update')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Form', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_update', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('date_delete', sa.DATETIME(), nullable=True))

    # ### end Alembic commands ###
