"""empty message

Revision ID: 5322de03abd4
Revises: bd328976ddcf
Create Date: 2023-04-08 13:30:17.721232

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5322de03abd4'
down_revision = 'bd328976ddcf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Form', schema=None) as batch_op:
        batch_op.drop_column('date_delete')
        batch_op.drop_column('date_update')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Form', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_update', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('date_delete', sa.DATETIME(), nullable=True))

    # ### end Alembic commands ###
