"""empty message

Revision ID: 8020e911f0e7
Revises: 
Create Date: 2023-04-10 00:23:18.981048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8020e911f0e7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Form',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('form', sa.String(), nullable=False),
    sa.Column('date_create', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('form'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Form')
    # ### end Alembic commands ###
